### PR TITLE
changes to regex to make it work again

### PR DESCRIPTION
**Pull request by dschaaff**

### CODE REVIEW

**Comment by dschaaff** [comment]
also happy to take on maintenance of this repo

**Comment by stopdropandrew** [comment]
if you want to move the repos to your account and link from these, or whatever, it's fine w/ me. just let me know

**Comment by dschaaff** [comment]
That sounds good. Then you don't have to bother with them. I'll look at how to swap them out in package control.

**Comment by dschaaff** [comment]
package control has tansferred over to my forks so you can remove this if you'd like. 

thanks again!

**Pull request closed without merging**
